import type { InsuranceState, ForensicOutput, Cpt } from '../../worker/types';
export interface ForensicTemplate {
  id: string;
  name: string;
  category: 'UNBUNDLING_DISPUTE' | 'BALANCE_BILLING_PROTECTION' | 'OON_NEGOTIATION';
  description: string;
  content: string;
}
export const APPEAL_TEMPLATES: ForensicTemplate[] = [
  {
    id: 'unbundling-dispute',
    name: 'Unbundling & Fragmented Billing Dispute',
    category: 'UNBUNDLING_DISPUTE',
    description: 'Used when providers bill multiple codes for components of a single procedure.',
    content: `
# FORMAL BILLING DISPUTE: UNBUNDLING FLAG {{DISPUTE_TOKEN}}
**TO:** Billing Department / Insurance Grievance Division
**DATE:** {{CURRENT_DATE}}
**RE:** Forensic Audit of Claim for CPT {{CPT}}
To Whom It May Concern,
I am writing to formally dispute the charges associated with the aforementioned claim based on a forensic audit identifying **Unbundled Billing Practices**.
### Forensic Findings
A deterministic analysis of the submitted codes reveals that CPT {{CPT}} and associated secondary codes represent components of a single, comprehensive procedure. Under standard National Correct Coding Initiative (NCCI) edits, these services are considered bundled and should not be billed as fragmented line items.
- **Identified Variance:** {{VARIANCE}}% above Fair Market Value (FMV)
- **Forensic Token:** {{DISPUTE_TOKEN}}
- **Liability Estimate:** ${{LIABILITY}}
### Strategic Request
I request a secondary review of this billing structure. Fragmentation of services to increase reimbursement is a violation of standard coding ethics. Please adjust the bill to reflect the comprehensive bundled rate for this procedure.
Sincerely,
[PATIENT NAME REDACTED]
*Generated by Legacy Navigator V2.1 Forensic Engine*
    `.trim()
  },
  {
    id: 'nsa-protection',
    name: 'No Surprises Act (NSA) Protection',
    category: 'BALANCE_BILLING_PROTECTION',
    description: 'Federal protection against balance billing for OON services at IN facilities.',
    content: `
# NOTICE OF PROTECTED HEALTHCARE RIGHTS (No Surprises Act)
**TO:** [PROVIDER/FACILITY NAME]
**DATE:** {{CURRENT_DATE}}
**RE:** Illegal Balance Billing for Protected Services
Pursuant to the **No Surprises Act (NSA)**, effective January 1, 2022, I am formalizing a dispute regarding the "Out-of-Network" (OON) charges applied to my recent visit.
### Legal Basis
The NSA prohibits providers from "balance billing" patients for emergency services or for non-emergency services provided by OON providers at In-Network facilities. My plan records indicate this facility is In-Network, thus triggering mandatory protection under **45 CFR § 149.410**.
### Forensic Audit Summary
- **Procedure Code:** CPT {{CPT}}
- **FMV Baseline:** ${{LIABILITY}}
- **Excess Variance Flagged:** {{VARIANCE}}%
- **Strategic Token:** {{DISPUTE_TOKEN}}
### Demand for Compliance
You are required by law to accept the Qualifying Payment Amount (QPA) as payment in full, excluding my standard In-Network cost-sharing. Any attempt to collect the balance beyond my deductible/co-insurance is a violation of federal law.
Sincerely,
[PATIENT NAME REDACTED]
    `.trim()
  },
  {
    id: 'oon-negotiation',
    name: 'OON Fair Market Value Negotiation',
    category: 'OON_NEGOTIATION',
    description: 'Negotiation script based on ERISA and Fair Market Value benchmarks.',
    content: `
# SETTLEMENT PROPOSAL: FAIR MARKET VALUE ADHERENCE
**TO:** Accounts Receivable Manager
**DATE:** {{CURRENT_DATE}}
**RE:** Proposal for Settlement of Account {{DISPUTE_TOKEN}}
I am reaching out to settle the outstanding balance for services rendered under CPT {{CPT}}. 
### Deterministic Benchmarking
A forensic review of regional Medicare-based Fair Market Value (FMV) benchmarks indicates that the billed amount represents a **{{VARIANCE}}% variance** from the national 80th percentile. 
### Proposal
Under **ERISA Section 502(a)** guidelines regarding fiduciary responsibility and reasonable charge limits, I am proposing a one-time settlement of **${{LIABILITY}}**. This amount represents 140% of the Medicare allowable rate, which is widely considered the ceiling for "reasonable and customary" reimbursement.
Please provide a written acceptance of this settlement or a revised invoice reflecting these forensic standards.
Sincerely,
[PATIENT NAME REDACTED]
    `.trim()
  }
];
export function getHydratedTemplate(
  templateId: string,
  data: {
    cpt?: string;
    variance?: number;
    disputeToken?: string | null;
    liability?: number;
  }
): string {
  const template = APPEAL_TEMPLATES.find(t => t.id === templateId) || APPEAL_TEMPLATES[0];
  let content = template.content;
  const replacements: Record<string, string> = {
    '{{CPT}}': data.cpt || '[CODE PENDING]',
    '{{VARIANCE}}': data.variance?.toString() || '0',
    '{{DISPUTE_TOKEN}}': data.disputeToken || 'NAV-GENERIC-VOID',
    '{{LIABILITY}}': data.liability?.toLocaleString() || '0.00',
    '{{CURRENT_DATE}}': new Date().toLocaleDateString(),
  };
  Object.entries(replacements).forEach(([key, value]) => {
    content = content.replace(new RegExp(key, 'g'), value);
  });
  return content;
}